application: sony-pmca
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /camera/xpd/.+
  script: main.app
  secure: optional
- url: /.*
  script: main.app
  secure: always
