github:
  clientId:
  clientSecret:
apps:
  Tweak:
    title: OpenMemories Tweak
    desc: Unlock camera settings
    repo: ma1co/OpenMemories-Tweak
  PMCADemo:
    title: PMCADemo
    desc: A demo app
    repo: ma1co/PMCADemo
